spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemaDatabase
    username: cinema
    password: cinema
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

paypal:
  client:
    id:
    secret: 
  mode: sandbox